# Site
name: "israelo.io"
title: "Israel Ogbole"
description: "Thoughts on IoT and Cloud Computing"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
blogurl: '/blog'
google_analytics: 'UA-186535929-1'
disqus: 'https-iogbole-github-io'
mailchimp-list: 'https://israelo.us7.list-manage.com/subscribe/post?u=53a3df9344e4aa53e567343bd&amp;id=6b55be21ac'
include: ["_pages"]
permalink: /blog/:title/
email: israel@israelo.io
formspree: "/f/xqkgwlbl"

#-------------------------------
# Hero Settings
hero:
  name: Israel Ogbole
  image: https://user-images.githubusercontent.com/2548160/103445496-98488300-4c6c-11eb-9d7e-7c02104a908e.png
  say-hello: Hello, Iâ€™m <strong>Israel Ogbole</strong>
  bio: I will use this space to share personal thoughts and experiences with Open Source Software, Raspberry Pi, Cloud-native technologies, and life in general. <br> Also, I will journal Naomi's programming journey here. Naomi is my nine-year-old daughter who loves coding.  
  twitter: https://twitter.com/israel_ogbole # Add your Twitter handle
  #facebook: https://facebook.com/ # Add your Facebook handle
  #instagram: https://instagram.com/ # Add your Instagram handle
  linkedin: https://www.linkedin.com/in/israelo
  github:  https://github.com/iogbole


# Authors
authors:
  israel:
    name: Israel
    display_name: Israel
    display_name_full: "Israel Ogbole"
    gravatar: 77792bd6ee4b9ddd999d004c6e8d9b2d
    email: israel@israelo.io
    web: https://www.linkedin.com/in/israelo/
    twitter: https://twitter.com/israel_ogbole
    description: "GirlDad, Engineering Product Manager, Solutions Architect, Software Consultant, MBA candidate, and now an occasional blogger "

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-redirect-from
    
# Archives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/blog/category/:name/'
    
# Pagination 
paginate: 20
paginate_path: "/blog/page:num/"
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
